### PR TITLE
feat: add a back button to 'Connect to remote screen'

### PR DESCRIPTION
**Pull request by krrprr**
Closes https://github.com/ExchangeUnion/xud-ui/issues/82

Changed the arrow icons in the `Next` buttons on the way so that they would be of the same style as the one in the `Back` button.

The release can be found [here](https://github.com/ExchangeUnion/xud-ui/releases/tag/v1.2.0-alpha.2).

### CODE REVIEW

**Review by kilrau — CHANGES_REQUESTED** [review]
- when entering from "Waiting for XUD Docker" landing screen, back returns to this
- when entering from a connected environments overview page back returns to this overview page

This behavior is technically correct, but what we really want is a way to return to the landing page that allows me to `Create`, `Connect` or `Restore`. So I propose to change the button to `Start` with a house icon.

**Review by erkarl — APPROVED** [review]

**Comment by erkarl** [comment]
Code wise approve.

**Comment by raladev** [comment]
> So I propose to change the button to `Start` with e.g. a house icon.

Disagree, Start is an action, i did not see any solution, that use Start as Returning to the home page.
Possible solution - Home with home icon, but it will not work for autoconnect page (because it is not home page).
So i suggest to keep it as is, Back button looks correct and organic.

**Review by raladev — COMMENTED** [review]
> So I propose to change the button to `Start` with e.g. a house icon.

Disagree, Start is an action, i did not see any solution, that use Start as Returning to the home page.
Possible solution - Home with home icon, but it will not work for autoconnect page (because it is not home page).
So i suggest to keep it as is, Back button looks correct and organic. @kilrau

**Comment by kilrau** [comment]
But still make back always return to the `Create` etc page? cc @peartobear

**Comment by raladev** [comment]
> But still make back always return to the `Create` etc page? cc @peartobear

for now we have no create page not for windows, should we remove Back button for mac and ubuntu then?

**Comment by krrprr** [comment]
> what we really want is a way to return to the landing page

I found the `Start` a bit confusing (could also be interpreted as _Start the connection_, although there's a `Connect` button as well).

I came up with another solution to achieve this.
* The `Back` button always redirects to home.
* Changed the dashboard `Disconnect` behavior on Windows (in the future when the landing page applies to others as well, all platforms would have the same behavior) so that it redirects to the home / landing page. Currently, Linux and Mac still redirect to the `Connect to remote` screen.
* In that case, the `Back` button redirecting home is accurate:
   - in case of Windows, the only place to access the `Connect to remote` screen is the home / landing page - no matter if disconnected from already accessed environment or just opened the app;
   - in case of Linux/Mac, when disconnected, the home pages remembers the recently accessed URL and reconnects to dashboard - so it's also basically going back to where the user was before.

I think the Disconnect button redirecting to the `Landing` page would make much more sense than the previous `Connect to remote` page, in case there is a `Landing` page.

Feel free to try out the solution @kilrau @raladev - [release](https://github.com/ExchangeUnion/xud-ui/releases/tag/v1.2.0-alpha.3)

**Review by raladev — APPROVED** [review]

**Comment by kilrau** [comment]
It's a bit weird that I can see the "Waiting for XUD Docker" screen for a split second before it is "going back to where the user was before", but honestly it's fine.

> I think the Disconnect button redirecting to the Landing page would make much more sense than the previous Connect to remote page, in case there is a Landing page.

Agreed.

Once linux and mac have a landing page, we'll clean it up. I created an issue for exactly that: https://github.com/ExchangeUnion/xud-ui/issues/112

**Review by kilrau — APPROVED** [review]

**Pull request merged**
